SELECT 
  COUNT(DISTINCT b1)
FROM
  (SELECT b1 FROM matches UNION ALL
  SELECT b2 FROM matches UNION ALL
  SELECT b3 FROM matches UNION ALL
  SELECT b4 FROM matches UNION ALL
  SELECT b5 FROM matches UNION ALL
  SELECT r1 FROM matches UNION ALL
  SELECT r2 FROM matches UNION ALL
  SELECT r3 FROM matches UNION ALL
  SELECT r4 FROM matches UNION ALL
  SELECT r5 FROM matches);